version: "3.8"

services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    ports:
      - "3001:3001"  # WebSocket（你的 Go 程序连接）
      - "6099:6099"  # WebUI 登录页面
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
    volumes:
      - ./napcat_data:/root/.local/share/NapCat
    restart: unless-stopped
